### ISSUE TITLE
Manual de usuario

### ISSUE THREAD

**Issue by ars0047** [gnx1001/GESPRO_GESTIONTAREAS#37]
- Requisitos de la app
- Instalación

**Comment by gnx1001** [comment]
[Add help contents](ea590a12c035e5a018bdfb47db44dab0c9aadb47) #37

**Comment by gnx1001** [comment]
@ars0047 
[Add video-tutorials](f466eff78292da1b2846a3688ed61e1d831af4b6) #37

**Comment by gnx1001** [comment]
[Minor fix](cffa887a03b01c113c93b4d2baf1f7b7d83e7844) #37

**Comment by gnx1001** [comment]
[ Improve help](0fe4a9c3c0dc764d721775ddc1bb7e7364248cc1) #37

**Comment by gnx1001** [comment]
[Improve display of videos](efffeaacd0257718dd1726852f3a1c2ba62c) #37

**Comment by gnx1001** [comment]
[Improve display of videos](d33476d87c73afa0d96e5ed0d579480763617fa5) #37
