### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by ars0047** [gnx1001/GESPRO_GESTIONTAREAS#39]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by gnx1001** [comment]
![imagen](https://user-images.githubusercontent.com/74902268/100550530-e4be2e80-327a-11eb-86c7-7035a7308106.png)
![imagen](https://user-images.githubusercontent.com/74902268/100550535-ea1b7900-327a-11eb-852e-e9159df4bed5.png)
![imagen](https://user-images.githubusercontent.com/74902268/100550541-f0115a00-327a-11eb-84fb-1c52c635412c.png)
![imagen](https://user-images.githubusercontent.com/74902268/100550544-f56ea480-327a-11eb-9e69-051655437c65.png)
![imagen](https://user-images.githubusercontent.com/74902268/100550545-facbef00-327a-11eb-91f1-6436913b916f.png)
![imagen](https://user-images.githubusercontent.com/74902268/100550547-fef80c80-327a-11eb-9cad-fd0f4bb95b97.png)

**Comment by gnx1001** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
