### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by ars0047** [gnx1001/GESPRO_GESTIONTAREAS#44]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by gnx1001** [comment]
![imagen](https://user-images.githubusercontent.com/74902268/100585964-b5490980-32ee-11eb-940e-27dee115fafa.png)

**Comment by gnx1001** [comment]
[ Fix exception with vectors in API < 21](ad9aebec669ddad347666772a53461777530478a) #44
