### ISSUE TITLE
Entrega TFG

### ISSUE THREAD

**Issue by gnx1001** [gnx1001/GESPRO_GESTIONTAREAS#45]
### A entregar:

- Secretaría:

- [x] Memoria en formato impreso.
- [x] Cinco discos memoria, anexos, fuentes del proyecto, aplicación, otros recursos (videos, máquinas virtuales, software open source de terceros...) .
- [x] Un disco con la memoria y anexos con dos resúmenes del trabajo (español y inglés).
- [x] [Impresos de solicitud.](https://www.ubu.es/escuela-politecnica-superior/estructura-del-centro/impresos-solicitudes-peticiones/trabajo-fin-de-grado)

- UbuVirtual:

- [x] Memoria y anexos en asignatura TFG.
- [x] Memoria y anexos en comunidad TFG.

**Comment by ars0047** [comment]
Impresos
impreso_biblioteca.docx
impreso_entrega_tfg.docx
